### ISSUE TITLE
outdated themes + irrelevant repo

### ISSUE THREAD

**Issue by liquidsquid1** [Razzy52/liquidthemes#9]
most themes are found on github now by searching “LiquidBounce theme”, and the rest of them are unfinished so no need for this repo to be up tbh.

**Comment by liquidsquid1** [comment]
lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.

**Comment by jesterwoohoo** [comment]
the person above me likes men

**Comment by EclipsesDev** [comment]
> lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.

then why don't u ask razzy for the rep permission to update stuff here 🗿

**Comment by jesterwoohoo** [comment]
> > lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.
> 
> then why don't u ask razzy for the rep permission to update stuff here 🗿

because hes a noob 👍

**Comment by liquidsquid1** [comment]
> > lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.
> 
> then why don't u ask razzy for the rep permission to update stuff here 🗿

because it shouldn’t be here? my themes are for people to compile and use from my repo, reuploading them here is just another chore that people shouldn’t need to do when they can get it straight from the source 🔥

**Comment by jesterwoohoo** [comment]
the person above me is gay

**Comment by EclipsesDev** [comment]
> > > lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.
> > 
> > 
> > then why don't u ask razzy for the rep permission to update stuff here 🗿
> 
> because it shouldn’t be here? my themes are for people to compile and use from my repo, reuploading them here is just another chore that people shouldn’t need to do when they can get it straight from the source 🔥

welp then womp womp

**Comment by Razzy52** [comment]
There is also no reason to take the repo down, I will leave it up.

**Comment by jesterwoohoo** [comment]
person above me is better

**Comment by DataM0del** [comment]
> the person above me is gay

the person I am quoting is gay

**Comment by DataM0del** [comment]
he's just trying to get his theme to the top of the search results anyways :skull:
